Repository AndelaOSP/Andela-Socials, pull requests merged in 2018-10, with the labels that each got.

#121 Add timezone to update schema
  server/graphql_schemas/event/schema.py
Labels: backend, bug

#125 Fix incorrect start and end date varriable name
  server/graphql_schemas/event/schema.py
Labels: backend, bug

#128 add eventID to update event
  client/components/Forms/EventForm.js
  client/pages/Dashboard/index.jsx
  client/pages/Event/EventDetailsPage.jsx
Labels: bug, frontend

#130 Add id to objects
  client/Graphql/Queries/EventGQL.js
  client/Graphql/Queries/EventListGQL.js
Labels: bug, frontend

#129 #161057741 Add script to confirm environment variables before start.
  .env.sample
  README.md
  scripts/checkEnv.sh
  scripts/start.sh
Labels: backend

#139 #161058605 Make event details page responsive
  client/assets/pages/_event_details-page.scss
  client/pages/Event/EventDetailsPage.jsx
Labels: frontend
