Repository AndelaOSP/Andela-Socials, pull requests merged in 2018-09, with the labels that each got.

#85 Bug #160226547: Add hover properties and adjust menu bar
  client/assets/components/navbar.scss
  client/components/common/Header.js
  client/components/common/NavBar.js
Labels: bug, frontend

#72 WIP: (Create/Update) event modal
  client/Graphql/Mutations/CreateEventGQL.js
  client/assets/base/globals.scss
  client/assets/components/common/form.scss
  client/assets/components/createEventBtn.scss
  client/assets/components/index.scss
  client/assets/components/modalContainer.scss
  client/assets/tools/variables.scss
  client/components/Forms/EventForm.js
  client/components/Modals/ModalContainer.js
  client/components/Modals/ModalContext.js
  client/components/common/Form/InputField.js
  client/components/common/Form/TextField.js
  client/components/common/Form/index.js
  client/components/common/Form/propsDefs.js
  client/pages/Dashboard/index.jsx
  client/utils/defaultProps.js
Labels: frontend, wip

#89 #160158027 Handle database error from multiple JoinCategory queries
  server/graphql_schemas/interest/schema.py
  server/graphql_schemas/tests/category/test_mutations.py
  server/graphql_schemas/tests/interest/snapshots/snap_test_mutations.py
  server/graphql_schemas/tests/interest/test_mutations.py
Labels: backend

#90 #160253921 Make category fields unique
  server/api/migrations/0019_auto_20180904_1109.py
  server/api/models.py
  server/graphql_schemas/category/schema.py
  server/graphql_schemas/tests/category/base.py
  server/graphql_schemas/tests/category/snapshots/snap_test_mutations.py
  server/graphql_schemas/tests/category/snapshots/snap_test_queries.py
  server/graphql_schemas/tests/category/test_mutations.py
  server/graphql_schemas/tests/interest/base.py
Labels: backend

#91 #160282500 Fix get events list implementation.
  client/Graphql/Queries/EventListGQL.js
  client/assets/components/_eventNotFound.scss
  client/assets/components/index.scss
  client/components/EventNotFound.jsx
  client/components/cards/EventCard.jsx
  client/components/common/NotFound.js
  client/pages/Event/EventsPage.jsx
Labels: frontend

#92 Fix apply button css
  client/components/filter/EventFilter.js
Labels: bug, frontend

#96 Fix errors on dashboard and eventpage
  client/pages/Dashboard/index.jsx
  client/pages/Event/EventsPage.jsx
Labels: bug, frontend

#98 [WIP] Add Additional Create Event Fields
  client/assets/components/common/form.scss
  client/assets/pages/_events-page.scss
  client/components/Forms/EventForm.js
  client/components/common/Form/DateTimePicker.js
  client/components/common/Form/InputField.js
  client/components/common/Form/TimePicker.js
  client/components/common/Form/UploadField.js
  client/components/common/Form/propsDefs.js
  client/components/common/IncrementalSelect.js
Labels: frontend

#95 #160388327 Update create event mutation with new fields
  client/Graphql/Mutations/CreateEventGQL.js
  client/actions/graphql/eventGQLActions.js
  client/components/TestActions/TestActions.js
Labels: frontend

#101 Connect create form to store
  client/actions/graphql/eventGQLActions.js
  client/components/Forms/EventForm.js
  client/components/Modals/ModalContainer.js
  client/pages/Dashboard/index.jsx
  client/pages/Event/EventsPage.jsx
  client/reducers/eventReducers.js
Labels: frontend

#102 #160483199 - Add dummy data to app
  README.md
  client/Graphql/Queries/CategoryGQL.js
  server/api/fixtures/initial.json
  server/api/fixtures/prod.json
Labels: backend

#106 Add category to events form
  client/assets/pages/_events-page.scss
  client/components/Forms/EventForm.js
  client/pages/Dashboard/index.jsx
Labels: frontend

#114 Fix category empty list on login
  client/pages/Dashboard/index.jsx
Labels: bug, frontend

#117 #160846610 Save event details on calendar error
  server/graphql_schemas/event/schema.py
Labels: backend
